walker:
  joints_controller:
    type: "position_controllers/JointGroupPositionController"
    publish_rate: 50
    joints:
      - lf_servo1
      - lf_servo2
      - lf_servo3
      - lm_servo1
      - lm_servo2
      - lm_servo3
      - lb_servo1
      - lb_servo2
      - lb_servo3
      - rf_servo1
      - rf_servo2
      - rf_servo3
      - rm_servo1
      - rm_servo2
      - rm_servo3
      - rb_servo1
      - rb_servo2
      - rb_servo3
